stages:
  - build_test
  - style_test
  - rebuild_database
  - functional_test
  - build_documentation
  - source_code_tar

test_build:
  stage: build_test
  tags:
    - build
  script:
    - make chess.so
  artifacts:
    paths:
      - lib/libchess.so
    expire_in: 30 days

test_style:
  stage: style_test
  tags:
    - style
  script:
    - clang-format -n -style=google -Werror src/*.cpp src/*.h src/Tests/*.cpp

build_database:
  stage: rebuild_database
  tags:
    - build
  script:
    - dropdb --if-exists chess
    - createdb chess
    - psql -f src/DataBase/ForTests.sql -d chess
  needs: ["test_style", "test_build"]

test_functional:
  stage: functional_test
  tags:
    - test
  script:
    - make test
  artifacts:
    paths:
      - build/chess
    expire_in: 30 days
  needs: ["build_database"]

documentation:
  stage: build_documentation
  tags:
    - build
  script:
    - make dvi
  artifacts:
    paths:
      - documentation
    expire_in: 30 days
  needs: [ "test_functional" ]

src_tar:
  stage: source_code_tar
  tags:
    - build
  script:
    - make dist
  artifacts:
    paths:
      - dist
    expire_in: 30 days
  needs: [ "test_functional" ]