stages:
  - build_test
  - style_test
  - rebuild_database
  - functional_test

test_build:
  stage: build_test
  tags:
    - build
  script:
    - make chess.so
  artifacts:
    paths:
      - lib/libchess.so
    expire_in: 30 days

test_style:
  stage: style_test
  tags:
    - style
  script:
    - clang-format -n -style=google -Werror src/*.cpp src/*.h src/Tests/*.cpp

build_database:
  stage: rebuild_database
  tags:
    - build
  script:
    - dropdb --if-exists chess
    - createdb chess
    - psql -f src/DataBase/ForTests.sql -d chess
  needs: ["test_style", "test_build"]

test_functional:
  stage: functional_test
  tags:
    - test
  script:
    - export DEBUG=$DEBUG
    - echo "'$DEBUG'"
    - make test
    - export DEBUG=0
  artifacts:
    paths:
      - build/chess
    expire_in: 30 days
  needs: ["build_database"]